name: binder_demo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  binder: ^0.4.0
  characters: ^1.0.0
  freezed_annotation: ^0.12.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  analyzer:
  freezed: ^0.12.2
  json_serializable: ^3.5.0
  http:
  flutter_lints: ^2.0.0

dependency_overrides:
  meta:

flutter:

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Medium.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

  uses-material-design: true

